name: Full Test

on:
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.13, 1.14, 1.15]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: git submodule update --init
    - name: Go Test
      run: go test ./...
    - name: Go Race Test
      run: go test -race ./...
