on:
  push:
    branches:
    - 'master'
    paths:
    - '**.go'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.go'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.15]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${ matrix.go-version }
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: git submodule update --init
    - name: Go Test
      run: go test -timeout 1h ./...
    - name: Go Race Test
      run: go test -timeout 1h -race ./...
