on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
    - '*'
    paths:
    - '**.go'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.go'
  # allow you to run this workflow manually from tab
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.15, 1.16]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Go Install
      run: go install ./...
    - name: Get dependencies
      run: git submodule update --init
    - name: Go Test
      run: go test -short ./...
